name: Deploy to IBM Cloud

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 21 * * 3"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip -o v2ray-linux-64.zip "v2ray" "v2ctl" "geosite.dat" "geoip.dat" 
        rm -rf v2ray-linux-64.zip
        chmod 700 v2ray v2ctl
        touch `date +%Y%m%d%H%M%S`
        cat > config.json << EOF
        {
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${{ secrets.CF_UUID_IBM }}",
                    "alterId": 64
                  }
                ]
              },
              "streamSettings": {
                "network":"ws"
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF
        
        cat > manifest-ibm.yml << EOF
        ---
        applications:
        - name: v2ws
          memory: 128M
          disk_quota: 128M
          random-route: true
          command: ./v2ray
          buildpacks:
          - binary_buildpack
        EOF
    
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.us-south.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: ${{ secrets.CF_ORG_IBM }}
        cf_space: ${{ secrets.CF_SPACE_IBM }}
        command: >
          push v2ws -f manifest-ibm.yml
          
